### PR TITLE
Florence 2018 insta

### PR DESCRIPTION
**Pull request by aappling-usgs**
4 lines of code change and a rebuild.

Insta format doesn't look great - I hope it's just my computer.

Before the new data filter:
gif_frame_a_20180918_09_nofilter

After the data filter:
gif_frame_a_20180918_09_withfilter

### CODE REVIEW

**Comment by lindsayplatt** [comment]
Hmm shouldn't instagram be a square? This seems shorter than it is wide.

**Comment by aappling-usgs** [comment]
Yes, it's not pretty. I'm hoping it's a Windows vs Mac thing. As you can see from the PR, I didn't edit the dimensions.

**Review by jordansread — APPROVED** [review]

**Comment by jordansread** [comment]
@lindsaycarr was doing some reading and seems portrait (w/ the aspect ratio used above) is better for insta animations. Square is still a good standard for the platform, but portrait gets us more real estate and maybe more impact.

**Comment by lindsayplatt** [comment]
Huh that's interesting. Cool 👍

**Comment by jordansread** [comment]
gif_frame_a_20180918_09
Here's what I have before the change

**Comment by aappling-usgs** [comment]
Yeah, that's nicer on Mac

**Pull request merged**
